import React from 'react'

const BlogPage = () => {
  return (
    <div className='container'>
      <h1>ブログ</h1>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Magni, qui. Enim repellat vel debitis id, nemo consequatur. Dolore, id numquam neque exercitationem ea quidem! Odio aperiam alias saepe voluptatum corrupti eaque. Tenetur expedita quia neque, nulla dolore explicabo beatae quibusdam repellendus ad hic. Accusantium natus facilis, ea molestias, minima laboriosam placeat fugit eum voluptatem molestiae minus doloremque tempora commodi odit iusto id eligendi nemo adipisci? Non quibusdam eius itaque aut. Tempore porro obcaecati illum cupiditate veritatis, amet, dolor accusantium iure enim, magni dolorum perferendis expedita cum quos numquam alias atque consectetur officiis eos! Repudiandae exercitationem magni qui repellendus quos officiis?</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Magni, qui. Enim repellat vel debitis id, nemo consequatur. Dolore, id numquam neque exercitationem ea quidem! Odio aperiam alias saepe voluptatum corrupti eaque. Tenetur expedita quia neque, nulla dolore explicabo beatae quibusdam repellendus ad hic. Accusantium natus facilis, ea molestias, minima laboriosam placeat fugit eum voluptatem molestiae minus doloremque tempora commodi odit iusto id eligendi nemo adipisci? Non quibusdam eius itaque aut. Tempore porro obcaecati illum cupiditate veritatis, amet, dolor accusantium iure enim, magni dolorum perferendis expedita cum quos numquam alias atque consectetur officiis eos! Repudiandae exercitationem magni qui repellendus quos officiis?</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Magni, qui. Enim repellat vel debitis id, nemo consequatur. Dolore, id numquam neque exercitationem ea quidem! Odio aperiam alias saepe voluptatum corrupti eaque. Tenetur expedita quia neque, nulla dolore explicabo beatae quibusdam repellendus ad hic. Accusantium natus facilis, ea molestias, minima laboriosam placeat fugit eum voluptatem molestiae minus doloremque tempora commodi odit iusto id eligendi nemo adipisci? Non quibusdam eius itaque aut. Tempore porro obcaecati illum cupiditate veritatis, amet, dolor accusantium iure enim, magni dolorum perferendis expedita cum quos numquam alias atque consectetur officiis eos! Repudiandae exercitationem magni qui repellendus quos officiis?</p>
      <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Magni, qui. Enim repellat vel debitis id, nemo consequatur. Dolore, id numquam neque exercitationem ea quidem! Odio aperiam alias saepe voluptatum corrupti eaque. Tenetur expedita quia neque, nulla dolore explicabo beatae quibusdam repellendus ad hic. Accusantium natus facilis, ea molestias, minima laboriosam placeat fugit eum voluptatem molestiae minus doloremque tempora commodi odit iusto id eligendi nemo adipisci? Non quibusdam eius itaque aut. Tempore porro obcaecati illum cupiditate veritatis, amet, dolor accusantium iure enim, magni dolorum perferendis expedita cum quos numquam alias atque consectetur officiis eos! Repudiandae exercitationem magni qui repellendus quos officiis?</p>

    </div>
  )
}

export default BlogPage;